name: "deployment"
on:
  push:
    branches:
      - main

jobs:
  deployment:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install stable rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install webkit2gtk (ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: install tauri-cli.rs
        run: cargo install tauri-cli --version ^1.0.0-beta
      - name: install npm dependencies
        run: npm install
      - name: build app
        run: npm run build
